import{S as l,i as u}from"./assets/vendor-5b791d57.js";(function(){const s=document.createElement("link").relList;if(s&&s.supports&&s.supports("modulepreload"))return;for(const t of document.querySelectorAll('link[rel="modulepreload"]'))i(t);new MutationObserver(t=>{for(const o of t)if(o.type==="childList")for(const n of o.addedNodes)n.tagName==="LINK"&&n.rel==="modulepreload"&&i(n)}).observe(document,{childList:!0,subtree:!0});function r(t){const o={};return t.integrity&&(o.integrity=t.integrity),t.referrerPolicy&&(o.referrerPolicy=t.referrerPolicy),t.crossOrigin==="use-credentials"?o.credentials="include":t.crossOrigin==="anonymous"?o.credentials="omit":o.credentials="same-origin",o}function i(t){if(t.ep)return;t.ep=!0;const o=r(t);fetch(t.href,o)}})();function d(e){const s="https://pixabay.com",r="/api/",t=`?key=42716405-8ee00579c2dae2c7c3ba8a313&q=${e}&image_type=photo&orientation=horizontal&safesearch=true`,o=s+r+t;return fetch(o).then(n=>{if(n.ok)return n.json();throw new Error(n.status)}).catch(n=>{console.log(n)})}const c=document.querySelector(".gallery");function p(e){return`<a href="${e.largeImageURL}" class="gallery-card">
          <img src="${e.webformatURL}" alt="${e.tags}" />
    
        <ul class="desc">
          <li class="desc-text">Likes<span>${e.likes}</span></li>
          <li class="desc-text">Views<span>${e.views}</span></li>
          <li class="desc-text">Comments<span>${e.comments}</span></li>
          <li class="desc-text">Downloads<span>${e.downloads}</span></li>
        </ul></a>`}function f(e){const s=e.hits.map(i=>p(i)).join("");c.innerHTML=s;let r=new l(".gallery a",m);r.on("show.simplelightbox"),r.refresh()}const m={captions:!0,captionSelector:"img",captionType:"attr",captionsData:"alt",captionPosition:"bottom",captionDelay:250},h=document.querySelector("form"),a=document.querySelector(".loader");h.addEventListener("submit",e=>{e.preventDefault(),c.innerHTML="";const s=e.target.elements.search.value;a.classList.remove("is-hidden"),d(s).then(r=>{r.hits.length===0?g():f(r),a.classList.add("is-hidden")}),e.target.reset()});function g(e){u.error({title:"Sorry, there are no images matching your search query. Please try again!",position:"topRight",titleColor:"#fff",backgroundColor:"#EF4040",titleSize:"16px",titleLineHeight:"1.5",close:!0,icon:""})}
//# sourceMappingURL=commonHelpers.js.map
