import{S as l,i as u}from"./assets/vendor-5b791d57.js";(function(){const r=document.createElement("link").relList;if(r&&r.supports&&r.supports("modulepreload"))return;for(const t of document.querySelectorAll('link[rel="modulepreload"]'))i(t);new MutationObserver(t=>{for(const o of t)if(o.type==="childList")for(const n of o.addedNodes)n.tagName==="LINK"&&n.rel==="modulepreload"&&i(n)}).observe(document,{childList:!0,subtree:!0});function s(t){const o={};return t.integrity&&(o.integrity=t.integrity),t.referrerPolicy&&(o.referrerPolicy=t.referrerPolicy),t.crossOrigin==="use-credentials"?o.credentials="include":t.crossOrigin==="anonymous"?o.credentials="omit":o.credentials="same-origin",o}function i(t){if(t.ep)return;t.ep=!0;const o=s(t);fetch(t.href,o)}})();function d(e){const r="https://pixabay.com",s="/api/",t=`?key=42716405-8ee00579c2dae2c7c3ba8a313&q=${e}&image_type=photo&orientation=horizontal&safesearch=true`,o=r+s+t;return fetch(o).then(n=>{if(n.ok)return n.json();throw new Error(n.status)})}const c=document.querySelector(".gallery");function p(e){return`<a href="${e.largeImageURL}" class="gallery-card">
          <img src="${e.webformatURL}" alt="${e.tags}" />
    
        <ul class="desc">
          <li class="desc-text">Likes<span>${e.likes}</span></li>
          <li class="desc-text">Views<span>${e.views}</span></li>
          <li class="desc-text">Comments<span>${e.comments}</span></li>
          <li class="desc-text">Downloads<span>${e.downloads}</span></li>
        </ul></a>`}function f(e){const r=e.hits.map(i=>p(i)).join("");c.innerHTML=r;let s=new l(".gallery a",m);s.on("show.simplelightbox"),s.refresh()}const m={captions:!0,captionSelector:"img",captionType:"attr",captionsData:"alt",captionPosition:"bottom",captionDelay:250},h=document.querySelector("form"),a=document.querySelector(".loader");h.addEventListener("submit",e=>{e.preventDefault(),c.innerHTML="";const r=e.target.elements.search.value;a.classList.remove("is-hidden"),d(r).then(s=>{s.hits.length===0?g():f(s),a.classList.add("is-hidden")}),e.target.reset()});function g(e){u.error({title:"Sorry, there are no images matching your search query. Please try again!",position:"topRight",titleColor:"#fff",backgroundColor:"#EF4040",titleSize:"16px",titleLineHeight:"1.5",close:!0,icon:""})}
//# sourceMappingURL=commonHelpers.js.map
